apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: express
build:
  artifacts:
  - image: anhdiepmmk/kub-first-app
    context: apps/express
    sync:
      manual:
        - src: '*.js'
          dest: '/app'
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yml
    - service.yml
