apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: infinity
build:
  artifacts:
  - image: dev.local/backend
    context: apps/backend
    sync:
      manual:
        - src: 'src/**/*'
          dest: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yml
    - service.yml
