apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          image: anhdiepmmk/kub-data-demo:v3
          volumeMounts:
            - mountPath: /app/love
              name: story-volume
      volumes:
        # - name: story-volume
        #   emptyDir: {}
        # - name: story-volume
        #   hostPath:
        #     path: /data
        #     type: DirectoryOrCreate
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc