apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          env:
            - name: STORY_FOLDER
              value: "love"
          image: anhdiepmmk/kub-data-demo:v1
          volumeMounts:
            - mountPath: /app/love
              name: story-volume
      volumes:
        # - name: story-volume
        #   emptyDir: {}
        # - name: story-volume
        #   hostPath:
        #     path: /data
        #     type: DirectoryOrCreate
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc