apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: story-ingress
spec:
  rules:
    - host: story.info
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: story-service
                port:
                  number: 8080